# 必须先启动master主节点
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
spec:
  selector:
    matchLabels:
      app: mysql-slave
      version: "5.7"
  serviceName: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
        version: "5.7"
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secret
          volumeMounts:
            - mountPath: /etc/mysql
              name: conf
            - mountPath: /var/lib/mysql
              name: data
      volumes:
        - name: conf
          configMap:
            name: mysql-slave-conf
            items:
              - key: my.cnf
                path: my.cnf
        - name: data
          hostPath:
            path: /var/lib/mysql-slave
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
spec:
  selector:
    app: mysql-slave
    version: "5.7"
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-public
spec:
  selector:
    app: mysql-slave
    version: "5.7"
  type: LoadBalancer
  ports:
    - port: 13306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-conf
data:
  my.cnf: |
    [mysqld]
    server-id=2
    log-bin=mysql-slave-bin
    relay_log=mysql-relay-bin