baseURL = "https://northes.io/"
defaultContentLanguage = "zh-cn"
title = "Northes"

theme = "hugo-tania"
enableRobotsTXT = true
enableGitInfo = false

[languages.zh-cn]
label = "简体中文"
weight = 1
locale = "zh-CN"

[pagination]
pzgerSize = 10

[params]
titleEmoji = "😃"
siteKeyword = "northes,Northes,blog,博客"
siteDesc = "Northes's Blog,Northes的博客。记录学习笔记以及过程中踩过的坑"
siteAuthor = "Northes"

[params.author]
name = "Northes"

[menu]
header = [
    #    { name = "Articles", url = "/articles/", weight = 1 },
    { name = "Tags", url = "/tags/", weight = 2 },
    { name = "Projects", url = "/projects/", weight = 3 },
    { name = "About", url = "/about/", weight = 4 },
]


[markup.highlight]
noClasses = false
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
