baseURL = "https://northes.co/"
languageCode = "zh-cn"
title = "Northes"
theme = "hugo-tania"

[params]
titleEmoji = "😃"

[menu]
header = [
    { name = "Articles", url = "/articles/", weight = 1 },
    { name = "About", url = "/about/", weight = 2 },
]


[markup.highlight]
noClasses = false
lineNos = true