apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
data:
  redis.conf: |+
    port 6379
    cluster-enabled yes
    cluster-node-timeout 5000
    cluster-config-file nodes.conf
    appendonly yes