apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  selector:
    app: redis-cluster
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
    - port: 16379
      targetPort: 16379
      protocol: TCP
      name: cluster
  type: LoadBalancer