apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
        - image: anjia0532/google-samples.node-hello:1.0
          name: hello-world
          ports:
            - containerPort: 8080

# 快速创建公开 Deployment 的 Service 对象 （LoadBalancer）
# kubectl expose deployment hello-world --type=LoadBalancer --name=my-service
