apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
      version: "5.7"
  template:
    metadata:
      labels:
        app: mysql
        version: "5.7"
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-secret
          volumeMounts:
            - mountPath: /etc/mysql
              name: conf
            - mountPath: /var/lib/mysql
              name: data
      volumes:
        - name: conf
          configMap:
            name: mysql-conf
            items:
              - key: my.cnf
                path: my.cnf
        - name: data
          hostPath:
            path: /var/lib/mysql
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
    version: "5.7"
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-public
spec:
  selector:
    app: mysql
    version: "5.7"
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
data:
  my.cnf: |
    [mysqld]
    #设置日志三种格式：STATEMENT、ROW、MIXED 。
    binlog_format = mixed
    #设置日志路径，注意路经需要mysql用户有权限写,这里可以写绝对路径,也可以直接写mysql-bin(后者默认就是在/var/lib/mysql目录下)
    log-bin = mysql-bin
    #设置binlog清理时间
    expire_logs_days = 7
    #binlog每个日志文件大小
    max_binlog_size = 100m
    #binlog缓存大小
    binlog_cache_size = 4m
    #最大binlog缓存大小
    max_binlog_cache_size = 512m
    #配置serverid
    server-id=1
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  password: MTIzNDU2 # 123456