# 私有镜像仓库认证信息
apiVersion: v1
kind: Secret
metadata:
  name: docker-tencent
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJjY3IuY2NzLnRlbmNlbnR5dW4uY29tIjp7InVzZXJuYW1lIjoiMTYyMDI3MDA5MyIsInBhc3N3b3JkIjoiMjkxODM5MjdhYmNkIiwiZW1haWwiOiIxNjIwMjcwMDkzQHFxLmNvbSIsImF1dGgiOiJNVFl5TURJM01EQTVNem95T1RFNE16a3lOMkZpWTJRPSJ9fX0=
# {"auths":{"ccr.ccs.tencentyun.com":{"username":"1620270093","password":"29183927abcd","email":"1620270093@qq.com","auth":"MTYyMDI3MDA5MzoyOTE4MzkyN2FiY2Q="}}}
# 需 base64