apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis-master
  serviceName: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis
          image: redis:6.2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
              name: redis
            - name: cluster
              containerPort: 16379
              protocol: TCP
          command:
            - sh
          args:
            - -c
            - redis-server /usr/local/etc/redis/redis.conf
          volumeMounts:
            - mountPath: /usr/local/etc/redis
              name: conf
      volumes:
        - name: conf
          configMap:
            name: redis-config
            items:
              - key: master.conf
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-master