apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-slave
  serviceName: redis-master
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis
          image: redis:6.2.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
            - name: cluster
              containerPort: 16379
              protocol: TCP
          command:
            - sh
          args:
            - -c
            - redis-server /usr/local/etc/redis/redis.conf
          volumeMounts:
            - mountPath: /usr/local/etc/redis
              name: conf
      volumes:
        - name: conf
          configMap:
            name: redis-config
            items:
              - key: slave.conf
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
spec:
  selector:
    app: redis-slave
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  clusterIP: None