apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis-slave
  serviceName: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - name: redis
          image: redis:6.2.6
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - redis-server /usr/local/etc/redis/redis.conf
          ports:
            - containerPort: 6379
              name: redis-slave
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/etc/redis
              name: conf
      volumes:
        - name: conf
          configMap:
            name: redis-config
            items:
              - key: slave.conf
                path: redis.conf
